name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
            sudo chmod -R 755 /home/lineadmin/ci
            sudo chown -R username:username /home/lineadmin/ci
            sudo setfacl -R -m u:www-data:rwx /home/lineadmin/ci
        
    - uses: actions/checkout@v2
    - name: Checking out the repository
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "*"
        target: "/home/lineadmin/ci"
      